### ISSUE TITLE
python3-cffi on apt is old

### ISSUE THREAD

**Issue by AndrewQuijano** [python-cffi/cffi#152]
Hello,
While I understand the main way to install python packages through pip, I also have been using apt to install packages as well. While most packages seem to have an updated version on apt, it seems CFFI only has a very old version 1.15 on apt. Is there any possibility that version 1.16 and 1.17 could be placed on apt so I can install it via `sudo apt-get install python3-cffi`? 

Thank you!

![image](https://github.com/user-attachments/assets/89dd7086-f115-4e0a-802f-6a03a3693087)

**Comment by arigo** [comment]
You should contact whoever is the author of the apt for cffi.  Here, we're only maintaining the original pip package.

**Comment by stefanor** [comment]
Stable Debian/Ubuntu releases carry the versions of packages that shipped at the time that the release froze. In jammy's case, that's early 2022.

If everything was continually updated, it wouldn't be very stable. For that, run the current development version, or a rolling release distro.
