### ISSUE TITLE
from_buffer with fortran ordered numpy array

### ISSUE THREAD

**Issue by AntoineD** [python-cffi/cffi#20]
Hello,

I'm trying to pass a contiguous fortran ordered (column major) numpy array to a library but I get an error.
Here is a reproducer:
```python
from cffi import FFI
import numpy as np
a=np.empty((2,2),order='F')
ffi = FFI()
ffi.from_buffer(a)
```

this gives
```console
File XXX/python3.8/site-packages/cffi/api.py:365, in FFI.from_buffer(self, cdecl, python_buffer, require_writable)
    363 elif isinstance(cdecl, basestring):
    364     cdecl = self._typeof(cdecl)
--> 365 return self._backend.from_buffer(cdecl, python_buffer,
    366                                  require_writable)

ValueError: ndarray is not C-contiguous
```

Is it the expected behavior?

**Comment by arigo** [comment]
As far as I can tell, yes: `ffi.from_buffer()` cannot return a pointer to a single C-style buffer of bytes because the F-ordered ndarray object stores that data in a way that is not a plain, flat contiguous range of bytes.  You'll have to find a way to convert the ndarray into a flat contiguous range of bytes (sorry, I don't know numpy enough to know how).

**Comment by PMeira** [comment]
To add some info here, assuming the library expects the F-ordered data, just transposing the array should be enough (same pointer, so no copies):

```python
>>> from cffi import FFI
>>> import numpy as np
>>> a = np.asarray([[1., 2.], [3., 4.]], order='F')
>>> print(a)
[[1. 2.]
 [3. 4.]]
>>> 
>>> # Same data/pointer, but different layouts reported
>>> assert a.ctypes.data == a.T.ctypes.data
>>> ffi = FFI()
>>> a_ffi = ffi.cast('double*', ffi.from_buffer(a.T))
>>> 
>>> print([a_ffi[0], a_ffi[1], a_ffi[2], a_ffi[3]]) # == a.T.ravel()
[1.0, 3.0, 2.0, 4.0]
>>> 
>>> a_ffi[2] = 300
>>> print(a)
[[  1. 300.]
 [  3.   4.]]
>>> 
```

I've seen some people using the raw ctypes pointer like `ffi.cast('double*', a.ctypes.data)`, but that's a bit risk -- if you forget to check for that, you (or your users) could accidentally pass an array with `order='C'` and not notice.

**Comment by AntoineD** [comment]
This is very clear, thank you both.
