### ISSUE TITLE
Wrapping _cffi_backend._CDataBase types

### ISSUE THREAD

**Issue by lacraig2** [python-cffi/cffi#26]
I would like to extend the functionality of various types in Python in a way that is largely transparent to the user and to cffi.

Let's say I have:

```C
struct Person {
    char *first_name;
    char *middle_name;
    char *last_name;
    int age;
}
```

To make a string representation of this object I might write the following code:

```python3
fname = ffi.string(p.first_name) if p.first_name != ffi.NULL else ""
mname = ffi.string(p.middle_name) if p.middle_name != ffi.NULL else ""
lname = ffi.string(p.last_name) if p.last_name != ffi.NULL else ""
p_str = f"{fname} {mname} {lname} {int(p.age)}
```

The problem is primarily where this code lives. I find that this code is written a lot and spread around the code base. You might make it a method, but then it's a utility that isn't associated with the object and doesn't benefit from the object oriented nature of Python.

As a straw man I'll put forward a concept of wrapping these types:

```Python  
class Person:    
    def __str__(self):
        fname = self.ffi.string(self.p.first_name) if self.p.first_name != self.ffi.NULL else ""
        mname = self.ffi.string(self.p.middle_name) if self.p.middle_name != self.ffi.NULL else ""
        lname = self.ffi.string(self.p.last_name) if self.p.last_name != self.ffi.NULL else ""
        return f"{fname} {mname} {lname} {int(self.p.age)}
 ```

The primary issue issue is that this is no longer transparent to CFFI. If I were to call a C function:

```Python
p  = Person(p1)
lib.function(p)
```

then cffi would issue an error that the object isn't of the right type. If instead `cffi` made a very simple wrapper available:

```Python
class CFFIWrapper:
    def __init__(self, ffi, obj):
        self.ffi = ffi
        self.obj = obj 

class Person:    
    def __str__(self):
        fname = self.ffi.string(self.p.first_name) if self.p.first_name != self.ffi.NULL else ""
        mname = self.ffi.string(self.p.middle_name) if self.p.middle_name != self.ffi.NULL else ""
        lname = self.ffi.string(self.p.last_name) if self.p.last_name != self.ffi.NULL else ""
        return f"{fname} {mname} {lname} {int(self.p.age)}
```

and checked for subclasses of `CFFIWrapper` on calls that substituted in some member (here: obj) then we could achieve a fully transparent experience with classes and C structs interacting.

I am looking for feedback on whether or not there are better ways of achieving this functionality. If this (or something similar) seems interesting I'd be happy to help implement it.

**Comment by arigo** [comment]
Hi Luke,

In my point of view, the "proper" way to approach these issues is to have
classes around all the C struct pointers exposed by CFFI, and never pass C
pointers around the rest of your program.  Your sample class Person is a
step in the right direction.  Take it all the way, and then you should
never have to call any of the `lib.xxx()` directly, but only from inside
methods of classes written with a Pythonic approach.  For example, add
methods:

    def get_first_name(self):
         return ffi.string(self._p.first_name) if self._p.first_name else
"<unspecified>"

or make that a property, as best fits your use case.  The same with the
function calls:

    def call_phone(self):
         return lib.call_phone_of(self._p)

It lets you cleanly separate the classes and the C struct pointers.  The
latter should only appear as some attribute (here `_p`), and read by the
methods that actually call the `lib.xxx()` C functions.  If properly
encapsulated, neither the `ffi` nor the `lib` object should be visible to
the rest of your program; these two can be globals in the file that
declares the class Person, but not elsewhere.

The details about how to do that encapsulation are beyond CFFI's purpose,
which is to give you low-level tools on top of which you can build
something.  I just described one approach, but it's by far not the only
possible one.


A bientôt,

Armin Rigo

**Comment by lacraig2** [comment]
Hi Armin,

I can understand your reasoning here.

Thanks for the reply!
-Luke
