### ISSUE TITLE
Due to license_file parameter deprecatioin, Unable to install cffi package

### ISSUE THREAD

**Issue by pvshingala1997** [python-cffi/cffi#27]
pip install 'cffi==1.14.6' --force-reinstall                                                                                                                                                              ─╯
Collecting cffi==1.14.6
  Downloading cffi-1.14.6.tar.gz (475 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.7/475.7 kB 863.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pycparser (from cffi==1.14.6)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: cffi
  Building wheel for cffi (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      /usr/local/lib/python3.9/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.cygwin-3.4.9-x86_64-cpython-39
      creating build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/api.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/backend_ctypes.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/cffi_opcode.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/commontypes.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/cparser.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/error.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/ffiplatform.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/lock.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/model.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/pkgconfig.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/recompiler.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/setuptools_ext.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/vengine_cpy.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/vengine_gen.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/verifier.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/__init__.py -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/_cffi_include.h -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/parse_c_type.h -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/_embedding.h -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      copying cffi/_cffi_errors.h -> build/lib.cygwin-3.4.9-x86_64-cpython-39/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.cygwin-3.4.9-x86_64-cpython-39
      creating build/temp.cygwin-3.4.9-x86_64-cpython-39/c
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.cygwin-3.4.9-x86_64-cpython-39/c/_cffi_backend.o
      c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
          2 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cffi
  Running setup.py clean for cffi
Failed to build cffi
ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects

**Comment by arigo** [comment]
The error you get is unrelated to `license_file`.  It's just a warning you can ignore.  The error is about `Python.h`.  See for example https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory or anything similar.

**Comment by haampie** [comment]
@arigo you closed this 7 days before it became a fatal error.
