### ISSUE TITLE
Error with cffi-1.15.1.tar.gz when performing pip install -r requirements.txt

### ISSUE THREAD

**Issue by zhongj3803** [python-cffi/cffi#31]
Collecting cffi==1.15.1 (from -r requirements.txt (line 45))
Using cached cffi-1.15.1.tar.gz (508 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [16 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "C:\Users\name\AppData\Local\Temp\pip-install-7tvsutzu\cffi_f224d2d0b6b44d45b77aab1b2eb9438b\setup.py", line 126, in
if sys.platform == "win32" and uses_msvc():
File "C:\Users\name\AppData\Local\Temp\pip-install-7tvsutzu\cffi_f224d2d0b6b44d45b77aab1b2eb9438b\setup.py", line 105, in uses_msvc
return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
File "C:\name\dir\dirr\venv\lib\python3.10\site-packages\setuptools_distutils\command\config.py", line 223, in try_compile
self._compile(body, headers, include_dirs, lang)
File "C:\name\dir\dirr\venv\lib\python3.10\site-packages\setuptools_distutils\command\config.py", line 128, in _compile
self.compiler.compile([src], include_dirs=include_dirs)
File "C:\name\dir\dirr\venv\lib\python3.10\site-packages\setuptools_distutils_msvccompiler.py", line 343, in compile
self.initialize()
File "C:\name\dir\dirr\venv\lib\python3.10\site-packages\setuptools_distutils_msvccompiler.py", line 246, in initialize
raise DistutilsPlatformError(
distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by arigo** [comment]
This looks like a generic distutils problem.  Does the following link help?  https://stackoverflow.com/questions/76079590/error-plat-name-must-be-one-of-win32-win-amd64-win-arm32-win-arm6

**Comment by zhongj3803** [comment]
> This looks like a generic distutils problem. Does the following link help? https://stackoverflow.com/questions/76079590/error-plat-name-must-be-one-of-win32-win-amd64-win-arm32-win-arm6

I ran

SETUPTOOLS_USE_DISTUTILS=stdlib pip install -r requirements.txt

but the error that shows up is

SETUPTOOLS_USE_DISTUTILS=stdlib : The term 'SETUPTOOLS_USE_DISTUTILS=stdlib' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ SETUPTOOLS_USE_DISTUTILS=stdlib pip install -r requirements.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SETUPTOOLS_USE_DISTUTILS=stdlib:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by arigo** [comment]
That's confusion because Windows has multiple different command line interpreters.  Try to type `set SETUPTOOLS_USE_DISTUTILS=stdlib` on its own line (note: it starts with `set`), and then `pip install -r requirements.txt` on the next line.

**Comment by arigo** [comment]
Also, maybe this link is specific to `msys2`, which you may not be using.  Try to google for other pages with the search for `distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')`

**Comment by zhongj3803** [comment]
Unfortunately I've not had any luck with getting a working solution on google. Is there anything else I can do?

**Comment by arigo** [comment]
Sorry I can't help you more myself.  My own experience with modern distutils/setuptools errors is quite limited.  The problem really looks generic and not related to cffi specifically.  I would suggest asking on stackoverflow; I will reach a lot of people who have a lot more experience than I do.

**Comment by zhongj3803** [comment]
> Sorry I can't help you more myself. My own experience with modern distutils/setuptools errors is quite limited. The problem really looks generic and not related to cffi specifically. I would suggest asking on stackoverflow; I will reach a lot of people who have a lot more experience than I do.

No worries, thank you for your time!

**Comment by PMeira** [comment]
I did some tests with different scenarios for a fresh Python 3.10 venv-- without MSVC (got the message pointing to the Build Tools, as expected), with MSVC 2019, and MSVC 2022, etc. and couldn't find any issue with up-to-date packages while building the CFFI  1.15.1. 

> (from -r requirements.txt (line 45))

Could it be some old package pinned from the requirements? @zhongj3803, would you mind listing the contents of that file? If it's not that, which Python distribution are you using? I could try reproducing more of the environment to try to reproduce the error.
