### ISSUE TITLE
Add `aarch64` `musllinux` wheel

### ISSUE THREAD

**Issue by sanmai-NL** [python-cffi/cffi#41]
When one runs Alpine Linux (e.g., a container) on a modern MacBook, there's no binary wheel available for `cffi`. It can cause build failures in environment set up to avoid compilations from source/sdists. Can you add a wheel for this setup?

**Comment by arigo** [comment]
@nitzmahone Any feedback on this request?

**Comment by n8felton** [comment]
@nitzmahone I noticed that #19 is currently in Draft and WIP, so I'm not sure if you'd want a PR against `main` to implement this, or if you want it added to nitzmahone:dynamic_build_matrix.

**Comment by ofek** [comment]
Has there been any update on this?

**Comment by strayge** [comment]
It would be awesome to see new wheels released on PyPI

**Comment by nitzmahone** [comment]
We'll likely do that within the next week or so- we're waiting for (thing I can't talk about yet), but if it doesn't happen in the next few days, I'll likely release what we have. Don't worry, it's not a CVE or anything, so if you want to use the build artifacts off the PR GHA run in the meantime, they should be good to go.
