### ISSUE TITLE
New breakage from 3.13.0a3

### ISSUE THREAD

**Issue by nitzmahone** [python-cffi/cffi#51]
Looks like there's at least one more C API change introduced by 3.13.0a3 we'll need to account for- it builds OK, but there's a new missing private symbol at import-time:

```
ImportError: /home/mdavis/.virtualenvs/tmp-65f3b135fc600df/lib/python3.13/site-packages/_cffi_backend.cpython-313-x86_64-linux-gnu.so: undefined symbol: _Py_HashPointer
```

**Comment by arigo** [comment]
Note also: https://github.com/python/cpython/issues/112026#issuecomment-1813191948
