### ISSUE TITLE
note in documentation another trigger for "Cannot allocate write+execute memory": systemd

### ISSUE THREAD

**Issue by fche** [python-cffi/cffi#73]
The readthedocs page that this write+execute callbacks message links people to mentions only selinux and a couple of other settings that can be responsible for this.  One that I just came across today was different from these.  On modern linux, systemd can install syscall filtering rules on services it supervises.  The MemoryDenyWriteExecute= setting in systemd.exec(5) defaults on, and can quietly block this.

Please consider mentioning systemd and that setting on the readthedocs page.

**Comment by arigo** [comment]
Thanks!  I've added a note to that page.  The readthedocs site might update now or later, I'm not sure.
